version: "1"
rules:                      # Array of rules
  - base: dev
    upstream: master        # Required. Can be a branch in the same forked repo.
    assignees:              # Optional
      - AdityaGupta150
    reviewers:              # Optional
      - AdityaGupta150
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - AdityaGupta150
label: ":arrow_heading_down: pull"  # Optional
